### ISSUE TITLE
Basic todo screen 

### ISSUE THREAD

**Issue by maritnl** [DAT251-Project-Groups-1/husfred#6]
- [ ] List of todos
- [ ] Add new todo button
- [ ] Mark todo as done
